version: 2

defaults: &defaults  
  docker:
    - image: timbru31/java-node:11-alpine-jdk

jobs:
  build:
    <<: *defaults
    steps:
      - checkout      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - save_cache:          
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /root/project
          paths:
            - node_modules
            - coverage  
  upload_report:
    <<: *defaults
    steps:      
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Submit Coverage
          command: npm run coverage
      - run:
          name: Submit sonar
          command: npm run sonar


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - upload_report:
          requires:
            - build
          filters:
            branches:
              only: master
      
