version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: loyaltyone/docker-alpine-java-node:jre-8-node-8   


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      #- run:
      #    name: Update npm
      #    command: 'npm install -g npm@latest'      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Install npm
          command: npm install
      - save_cache:          
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /root/app
          paths:
            - node_modules
  test:
    <<: *defaults    
    steps:      
      - checkout
      - attach_workspace:
          at: /root/app
      - run:
          name: Test
          command: npm test
  upload_report:
    <<: *defaults
    steps:      
      - checkout
      - attach_workspace:
          at: /root/app
      - run:
          name: Submit Coverage
          command: npm run coverage
      - run:
          name: Submit sonar
          command: npm run sonar
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload_report:
          requires:
            - test
          filters:
            branches:
              only: master
      