version: 2
jobs:
  build:
    docker:      
      - image: loyaltyone/docker-alpine-java-node:jre-8-node-8   
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Install npm
          command: npm install
      - save_cache:          
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: loyaltyone/docker-alpine-java-node:jre-8-node-8   
    step:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Submit Coverage
          command: npm run coverage
      - run:
          name: Submit sonar
          command: npm run sonar
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build
            filter:
              branches:
                only: master